{% set name = "ConfigArgParse" %}
{% set version = "1.8.0" %}

# Upstream source - https://github.com/bw2/ConfigArgParse/blob/v1.7.7/setup.py
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/C/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 22a417f4d7b00149f0af82ef7c491f8ecc4b1d5454633fd319b386f5eb806f92

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<36]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
    - setuptools-scm
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - configargparse
  requires:
    - pyyaml
    - pip
    - pytest
    - toml
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -vv tests

about:
  home: https://github.com/bw2/ConfigArgParse
  summary: |
    Applications with more than a handful of user-settable options are best configured through a combination of command line args,
    config files, hard-coded defaults, and in some cases, environment variables.
  description: |
    A drop-in replacement for argparse that allows options to
    also be set via config files and/or environment variables.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/bw2/ConfigArgParse
  doc_url: https://bw2.github.io/ConfigArgParse

extra:
  recipe-maintainers:
    - msarahan
    - bollwyvl
