{% set version = "1.4.1" %}

package:
  name: configargparse
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/C/ConfigArgParse/ConfigArgParse-{{ version }}.tar.gz
  sha256: 6df537158f28c5ef2e8a8146781833abbc6cb7fca81b1b55d18808ce3439235e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python >=2.7
    - pip
    - setuptools
    - wheel
  run:
    - python >=2.7
    - pyyaml

test:
  source_files:
    - tests
    - setup.py
    # 5/27/2021: To fix an error message "file configargparse.py (for module configargparse) not found"
    - configargparse.py  # [win]
  requires:
    - mock
    - pyyaml
    - pip
    - pytest
  imports:
    - configargparse
  commands:
    - python -m pip check
    - pytest
    #- python -m setup.py test

about:
  home: https://github.com/bw2/ConfigArgParse
  license: MIT
  summary: A drop-in replacement for argparse that allows options to also be set via config files and/or environment variables.
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/bw2/ConfigArgParse
  doc_url: https://github.com/bw2/ConfigArgParse

extra:
  recipe-maintainers:
    - msarahan
    - bollwyvl
