{% set version = "1.1" %}

package:
  name: configargparse
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/C/ConfigArgParse/ConfigArgParse-{{ version }}.tar.gz
  sha256: 7971cdb14328baaada0f140832925de83ecee93ac5e67e587e3476fac283ad51

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  source_files:
    - tests
    - setup.py
  requires:
    - pyyaml
    - pip
  imports:
    - configargparse
  commands:
    - python setup.py test

about:
  home: https://github.com/zorro3/ConfigArgParse
  license: MIT
  summary: A drop-in replacement for argparse that allows options to also be set via config files and/or environment variables.
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/zorro3/ConfigArgParse
  doc_url: https://github.com/zorro3/ConfigArgParse

extra:
  recipe-maintainers:
    - msarahan
    - bollwyvl
