{% set version = "1.3" %}

package:
  name: configargparse
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/C/ConfigArgParse/ConfigArgParse-{{ version }}.tar.gz
  sha256: 0428b975ab6c48bb101ccb732e1b5cb616296e28268e032aa806f32b647a1cc1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  source_files:
    - tests
    - setup.py
  requires:
    - pyyaml
    - pip
  imports:
    - configargparse
  commands:
    - python setup.py test
    - python -m pip check

about:
  home: https://github.com/bw2/ConfigArgParse
  license: MIT
  summary: A drop-in replacement for argparse that allows options to also be set via config files and/or environment variables.
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/bw2/ConfigArgParse
  doc_url: https://github.com/bw2/ConfigArgParse

extra:
  recipe-maintainers:
    - msarahan
    - bollwyvl
