travis:
  secure:
    BINSTAR_TOKEN: FW3/BiJAtT+cSdXKwHIGy4zU666tpvOuLy5NySIKDI9SENs+dvl0K5cEqWWPRS16CsFVJeSFk/w3Z+p4W7w5WiACvs0iDSPUGJO0T3ze9335y7w4KuPdI2aLpOsyAJKf4jcM7QSPmpdZEKANBk2aupC/Ve7j1+nGPxRgGq2XCXVeUN2huXs0cAi3SH9pk3uS3DJ7d2yRKCnUqHyON5MIIhVVo+q/ZSgH7aJLB5IXAKSOSLvZkdYXoFI1GPNjGfEliogLQ3KasuEyApQL2jZyZSaR2YT+5UFL2P4Gnc9i8BeJnryFBMdvh/G0V8AiMikdzGqwNFUzWPAKc8oY1fc+5QAbZh/XOKxNNoria1uATUE+zsup+V3o7R4Zw/kzv5WfvgvM1tuXw7FD2fsBVBH/y4r3AwlvfHNgPMwWK8iaFB+EMZlzWvQJFv5DS+vCVIj+qDLMOfMMAa68yd3A/iuTpjEz4yKXPBPfDNoh5q3KEG/QSJh896hb5xIbIK8Xc8NZ+3mAN5MLb8BHIuOcSUdMdHDUXBL5mRxm/R0yg5RIg8iVP+M4qE2YOgor1jz/SAFt8DpsAxl7yVJvyH0gz0Ts5Nqnzj6M1dcqCv5HPp+CCw4Xlv9ZlPvP9BnWye9j2YYwbhd63PgypIHeRP6Wr83/C1XOmiBeNiaVENqhNWb/6QM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
